# Generated by Django 4.2 on 2025-05-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=55)),
                ('lastname', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('contact_number', models.CharField(max_length=55)),
                ('total_rent', models.IntegerField(default=0)),
                ('valid_id', models.ImageField(upload_to='./static/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
