# Generated by Django 4.2 on 2025-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
