# Generated by Django 4.2.8 on 2025-06-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='recent_pickups',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
