# Generated by Django 4.2 on 2025-06-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers_recent_pickups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='recent_pickups',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
