# Generated by Django 4.2.8 on 2025-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers_recent_pickups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='last_rental_date',
            field=models.DateField(blank=True, default=models.DateTimeField(auto_now_add=True), help_text='Date of the last rental'),
        ),
    ]
