# Generated by Django 4.2 on 2025-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customers_recent_pickups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='last_rent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
