# Generated by Django 4.2 on 2025-06-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customers_last_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
