# Generated by Django 4.2.8 on 2025-06-03 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customers_last_rental_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='last_rental_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
