# Generated by Django 4.2 on 2025-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('equipment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('category', models.CharField(max_length=55)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_quantity', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='./static/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
