# Generated by Django 4.2 on 2025-05-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='image',
            field=models.ImageField(upload_to='../static/images/'),
        ),
    ]
