# Generated by Django 4.2 on 2025-06-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='utilizations',
            field=models.IntegerField(default=0),
        ),
    ]
