# Generated by Django 4.2 on 2025-05-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_equipments_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipments',
            old_name='rental_id',
            new_name='equipment_id',
        ),
        migrations.AlterField(
            model_name='equipments',
            name='image',
            field=models.ImageField(upload_to='./static/images/'),
        ),
    ]
