# Generated by Django 4.2 on 2025-06-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_alter_customers_created_at'),
        ('inventory', '0003_equipments_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='rental',
            fields=[
                ('calculated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_pickup', models.BooleanField(default=False)),
                ('rental_date', models.DateField(help_text='Date when the equipment rental starts')),
                ('due_date', models.DateField(help_text='Date when the equipment should be returneds')),
                ('return_date', models.DateField(blank=True, help_text='Actual date when equipment was returned', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the rental', null=True)),
                ('rental_agreement', models.ImageField(blank=True, help_text='Upload rental agreement document', null=True, upload_to='./static/images')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rentals', to='customers.customers')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_rentals', to='inventory.equipments')),
            ],
        ),
    ]
