# Generated by Django 4.2 on 2025-05-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_agreement',
            field=models.ImageField(blank=True, help_text='Upload rental agreement document', null=True, upload_to='./static/images'),
        ),
    ]
