# Generated by Django 4.2 on 2025-05-31 18:10

from django.db import migrations

def forwards(apps, schema_editor):
    Rental = apps.get_model('booking', 'Rental')
    for rental in Rental.objects.all():
        rental.calculated_amount = rental.total_amount  # Uses your property
        rental.save(update_fields=['calculated_amount'])
class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rental_calculated_amount'),
    ]
    

    operations = [migrations.RunPython(forwards)]

