# Generated by Django 4.2 on 2025-06-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rental_calculated_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
