# Generated by Django 4.2 on 2025-06-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rental_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='quantity',
        ),
    ]
