# Generated by Django 4.2 on 2025-06-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_rental_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='rental',
            name='last_status_check',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['rental_date'], name='booking_ren_rental__c06c67_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['due_date'], name='booking_ren_due_dat_c0faba_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['status'], name='booking_ren_status_b6e2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['last_status_check'], name='booking_ren_last_st_703065_idx'),
        ),
    ]
