# Generated by Django 4.2 on 2025-06-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_rental_options_rental_last_status_check_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='booking_ren_rental__c06c67_idx',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='booking_ren_due_dat_c0faba_idx',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='booking_ren_status_b6e2f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='booking_ren_last_st_703065_idx',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='last_status_check',
        ),
    ]
