# Generated by Django 4.2 on 2025-06-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_rental_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
